### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/onyo#326]
I know, 1.0.0 is a controversial title, but I want to collect, describe and discuss all aspects (features to implement and bugs to resolve) which I consider a strong requirement for the first stable version of Onyo, before we share and request further testing by others.
These changes require more coordination, so they should be done after the realease of the next version with #323!

- [ ] The path issue (and tests for it):
  - [x] #206
    - [x] Together with #325
  - [x] #142
  - [x] #259
  - [x] #284 

- [ ] modernize fsck (maybe complete implementation is not needed, but parts are relevant)
  - [x] #107 
  - [ ] #176 

- [x] printing overhaul for user-visible parts:
  - [x] #255 
  - [x] #305
  - [x] pretty-fy existing output for commands, some look not nice

- [ ] fuller `.onyo/` support:
  - [ ]  #306
  - [ ] especially adding functionality to add/modify templates is needed 

- [x] smoothing, cleaning up and completing work already started:
  - [x] #14
  - [x] #113 
  - [x] #286
  - [x] #266
  - [x] #285 
  - [x] #296
  - [x] #298 (just some code-moving)
  - [x] #301 (just adding some `except:` and then cleaning up, after #298 is solved)

- [ ] API demo #309

- [ ] documentation
  - [ ] no issue, but so many parts do not reflect the current state of Onyo, this needs to be fixxed!
  - [ ] #105 
  - [ ] #17 (this should be based on the demo repository)
  - [ ] #146

**Comment by aqw** [comment]
I removed colorized output from the list.

**Comment by TobiasKadelka** [comment]
https://github.com/psyinfra/onyo/issues/236

We might want to consider "making faux serial number length flexible" together with the fuller .onyo support, since it would probably be configured in `.onyo/config`.

**Comment by TobiasKadelka** [comment]
It is planned to replace this issue with mile stones -- when that happens, the same should be done for #386 too!

**Comment by bpoldrack** [comment]
Milestone exists. Closing this one.
